### ISSUE TITLE
Don't assume /bin/sh is bash-compatible

### ISSUE THREAD

**Issue by foxdevilwild** [severoraz/todotxt-cli-tedit#1]
Ubuntu, per default, links /bin/sh to dash which breaks the script. Fix is simple: call /bin/bash directly or don't rely on bashisms. I'd be happy to provide a PR for either solution.

**Comment by severoraz** [comment]
Thank you for the bug report, I'm not sure why I thought using sh would make the script more compatible, if todo.sh itself uses bash haha. Anyway, I've changed it today, please let me know if it works. If it doesn't, please let me know which error is spit out.

**Comment by foxdevilwild** [comment]
Works. Thanks for fixing!

**Comment by severoraz** [comment]
Glad to help!
